# Generated by Django 5.2.8 on 2025-12-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_achievement_profile_avatar_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_add_custom_subjects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_use_ai_chatbot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_subjects',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('free', 'Gratuito'), ('student', 'Estudiante'), ('personal', 'Personal'), ('enterprise', 'Empresa')], max_length=50, unique=True),
        ),
    ]
